// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using LoLEnemyChampionWinratesASP.Models;
//
//    var matchListInfo = MatchListInfo.FromJson(jsonString);

namespace LoLEnemyChampionWinratesASP.Models
{
	using System;
	using System.Collections.Generic;

	using System.Globalization;
	using Newtonsoft.Json;
	using Newtonsoft.Json.Converters;

	public class MatchListInfo
	{
		public static List<string> FromJson(string json) => JsonConvert.DeserializeObject<List<string>>(json, LoLEnemyChampionWinratesASP.Helpers.Converter.Settings);
	}

	public static partial class Serialize
	{
		public static string ToJson(this List<string> self) => JsonConvert.SerializeObject(self, LoLEnemyChampionWinratesASP.Helpers.Converter.Settings);
	}
}